import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# x = ["id", "Submit_Time", "Wait_Time", "Run_Time", "NAP", "RNP", "User_ID", "Queue_Number"]
# y = [339201681, 828210292, 182352322, 407366457, 98230044, 98230044, 20160504, 15931294]
# fig, ax = plt.subplots(figsize=(10, 7))
# # 设置刻度字体大小
# plt.xticks(fontsize=15, rotation=15, weight='bold')
# plt.yticks(fontsize=15, weight='bold')
# ax.set_ylabel('Scores', fontsize=15, weight='bold')
# ax.set_xlabel('Features', fontsize=15, weight='bold')
# ax.bar(x=x, height=y, width=0.5)
# ax.set_title("SelectKBest", fontsize=20, weight='bold')
# plt.savefig('E:\paper\\2203\\figures\skb.png', bbox_inches='tight', dpi=128)
#
# x2 = ["id", "Submit_Time", "Wait_Time", "Run_Time", "NAP", "RNP", "User_ID", "Queue_Number"]
# y2 = [-19124.564, -12148.496, 2494.202, -5203.794, 19331.822, 19331.822, 19220.976, 19354.746]
# fig2, ax = plt.subplots(figsize=(10, 7))
# # 设置刻度字体大小
# plt.xticks(fontsize=15, rotation=15, weight='bold')
# plt.yticks(fontsize=15, weight='bold')
# ax.set_ylabel('Scores', fontsize=15, weight='bold')
# ax.set_xlabel('Features', fontsize=15, weight='bold')
# ax.axhline(0, color='gray', linewidth=0.8)
# ax.bar(x=x2, height=y2, width=0.5)
# ax.set_title("ReliefF", fontsize=20, weight='bold')
# plt.savefig('E:\paper\\2203\\figures\\rrff.png', bbox_inches='tight', dpi=128)
# plt.show()

# 预测结果折线图

plt.figure(figsize=(20, 9), dpi=200)
data1 = pd.read_csv("D:\pythonProject\spark\datas\\result\LGBpredictionNoCV.csv", nrows=300)
data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\RFpredictionNoCV.csv", nrows=300)
data3 = pd.read_csv("D:\pythonProject\spark\datas\\result\DTpredictionNoCV.csv", nrows=300)
data4 = pd.read_csv("D:\pythonProject\spark\datas\\result\KNNpredictionNoCV.csv", nrows=300)
data5 = pd.read_csv("D:\pythonProject\spark\datas\\result\SVMpredictionNoCV.csv", nrows=300)
data6 = pd.read_csv("D:\pythonProject\spark\datas\\result\GDBTpredictionNoCV.csv", nrows=300)

data01 = pd.read_csv("D:\pythonProject\spark\datas\\result\LGBtrueNoCV.csv", nrows=300)
data02 = pd.read_csv("D:\pythonProject\spark\datas\\result\RFtrueNoCV.csv", nrows=300)
data03 = pd.read_csv("D:\pythonProject\spark\datas\\result\DTtrueNoCV.csv", nrows=300)
data04 = pd.read_csv("D:\pythonProject\spark\datas\\result\KNNtrueNoCV.csv", nrows=300)
data05 = pd.read_csv("D:\pythonProject\spark\datas\\result\SVMtrueNoCV.csv", nrows=300)
data06 = pd.read_csv("D:\pythonProject\spark\datas\\result\GDBTtrueNoCV.csv", nrows=300)
fig, axs = plt.subplots(2, 3, figsize=(30, 10), dpi=200)
axs[0, 0].plot(data1, color='red', label="Label")
axs[0, 0].plot(data01, color='blue', label="Prediction")
axs[0, 0].set_title('LGBM')
axs[0, 0].legend(loc=0)
axs[0, 1].plot(data2, color='red', label="Label")
axs[0, 1].plot(data02, color='blue', label="Prediction")
axs[0, 1].set_title('Random Forest')
# axs[0, 1].legend(loc=0)
axs[0, 2].plot(data3, color='red', label="Label")
axs[0, 2].plot(data03, color='blue', label="Prediction")
axs[0, 2].set_title('DecisionTree')
# axs[0, 2].legend(loc=0)
axs[1, 0].plot(data4, color='red', label="Label")
axs[1, 0].plot(data04, color='blue', label="Prediction")
axs[1, 0].set_title('KNN')
# axs[1, 0].legend(loc=0)
axs[1, 1].plot(data5, color='red', label="Label")
axs[1, 1].plot(data05, color='blue', label="Prediction")
axs[1, 1].set_title('SVM')
# axs[1, 1].legend(loc=0)
axs[1, 2].plot(data6, color='red', label="Label")
axs[1, 2].plot(data06, color='blue', label="Prediction")
axs[1, 2].set_title('GDBT')
# axs[1, 2].legend(loc=0)
plt.savefig('E:\paper\\2203\\figures\\REFall.png', bbox_inches='tight', dpi=128)
# ax1 = plt.subplot(221)
# ax1.plot(data1, color='red', label="Label")
# ax1.plot(data01, color='blue', label="Prediction")
# ax2 = plt.subplot(222)
# ax2.plot(data2, color='red', label="Label")
# ax2.plot(data02, color='blue', label="Prediction")
# ax3 = plt.subplot(223)
# ax3.plot(data3, color='red', label="Label")
# ax3.plot(data03, color='blue', label="Prediction")
# ax4 = plt.subplot(224)
# ax4.plot(data4, color='red', label="Label")
# ax4.plot(data04, color='blue', label="Prediction")
# ax5 = plt.subplot(225)
# ax5.plot(data5, color='red', label="Label")
# ax5.plot(data05, color='blue', label="Prediction")
# ax6 = plt.subplot(226)
# ax6.plot(data6, color='red', label="Label")
# ax6.plot(data06, color='blue', label="Prediction")
# # data = pd.read_csv("D:\pythonProject\spark\datas\\result\LGBpredictionNoCV.csv", nrows=400)
# # data = pd.read_csv("D:\pythonProject\spark\datas\\result\RFpredictionNoCV.csv", nrows=400)
# # data = pd.read_csv("D:\pythonProject\spark\datas\\result\DTpredictionNoCV.csv", nrows=400)
# # data = pd.read_csv("D:\pythonProject\spark\datas\\result\KNNpredictionNoCV.csv",nrows=400)
# # data = pd.read_csv("D:\pythonProject\spark\datas\\result\SVMpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\GDBTpredictionNoCV.csv", nrows=400)
#
# # data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\LGBtrueNoCV.csv", nrows=400)
# # data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\RFtrueNoCV.csv", nrows=400)
# # data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\DTtrueNoCV.csv", nrows=400)
# # data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\KNNtrueNoCV.csv", nrows=400)
# # data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SVMtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\GDBTtrueNoCV.csv", nrows=400)
#
# # x = range(1, 401, 10)
# plt.plot(data2, color='red', label="Label")
# plt.plot(data, color='blue', label="Prediction")
# plt.legend(loc=0)
# # plt.xticks(x)
# # plt.title("LightGBM")
# # plt.title("Random Forest")
# # plt.title("DecisionTree")
# # plt.title("KNN")
# # plt.title("SVM")
# plt.title("GDBT")
# plt.ylabel("Status")
# # plt.savefig('E:\paper\\2203\\figures\\LGB.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\RF.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\DT.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\KNN.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\SVM.png', bbox_inches='tight', dpi=128)
# plt.savefig('E:\paper\\2203\\figures\\GDBT.png', bbox_inches='tight', dpi=128)
plt.show()
