import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator, FormatStrFormatter, Locator
import pandas as pd

# x = ["id", "Submit_Time", "Wait_Time", "Run_Time", "NAP", "RNP", "User_ID", "Queue_Number"]
# y = [339201681, 828210292, 182352322, 407366457, 98230044, 98230044, 20160504, 15931294]
# fig, ax = plt.subplots(figsize=(10, 7))
# # 设置刻度字体大小
# plt.xticks(fontsize=15, rotation=15, weight='bold')
# plt.yticks(fontsize=15, weight='bold')
# ax.set_ylabel('Scores', fontsize=15, weight='bold')
# ax.set_xlabel('Features', fontsize=15, weight='bold')
# ax.bar(x=x, height=y, width=0.5)
# ax.set_title("SelectKBest", fontsize=20, weight='bold')
# plt.savefig('E:\paper\\2203\\figures\skb.png', bbox_inches='tight', dpi=128)
#
# x2 = ["id", "Submit_Time", "Wait_Time", "Run_Time", "NAP", "RNP", "User_ID", "Queue_Number"]
# y2 = [-19124.564, -12148.496, 2494.202, -5203.794, 19331.822, 19331.822, 19220.976, 19354.746]
# fig2, ax = plt.subplots(figsize=(10, 7))
# # 设置刻度字体大小
# plt.xticks(fontsize=15, rotation=15, weight='bold')
# plt.yticks(fontsize=15, weight='bold')
# ax.set_ylabel('Scores', fontsize=15, weight='bold')
# ax.set_xlabel('Features', fontsize=15, weight='bold')
# ax.axhline(0, color='gray', linewidth=0.8)
# ax.bar(x=x2, height=y2, width=0.5)
# ax.set_title("ReliefF", fontsize=20, weight='bold')
# plt.savefig('E:\paper\\2203\\figures\\rrff.png', bbox_inches='tight', dpi=128)
# plt.show()

# 预测结果折线图
# plt.figure(figsize=(20, 9), dpi=200)
# data1 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\LGBpredictionNoCV.csv", nrows=300)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\RFpredictionNoCV.csv", nrows=300)
# data3 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\DTpredictionNoCV.csv", nrows=300)
# data4 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\KNNpredictionNoCV.csv", nrows=300)
# data5 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\SVMpredictionNoCV.csv", nrows=300)
# data6 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\GDBTpredictionNoCV.csv", nrows=300)
#
# data01 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\LGBtrueNoCV.csv", nrows=300)
# data02 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\RFtrueNoCV.csv", nrows=300)
# data03 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\DTtrueNoCV.csv", nrows=300)
# data04 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\KNNtrueNoCV.csv", nrows=300)
# data05 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\SVMtrueNoCV.csv", nrows=300)
# data06 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\GDBTtrueNoCV.csv", nrows=300)

# data1 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\LGBpredictionNoCV.csv", nrows=300)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\RFpredictionNoCV.csv", nrows=300)
# data3 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\DTpredictionNoCV.csv", nrows=300)
# data4 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\KNNpredictionNoCV.csv", nrows=300)
# data5 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\SVMpredictionNoCV.csv", nrows=300)
# data6 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\GDBTpredictionNoCV.csv", nrows=300)
#
# data01 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\LGBtrueNoCV.csv", nrows=300)
# data02 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\RFtrueNoCV.csv", nrows=300)
# data03 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\DTtrueNoCV.csv", nrows=300)
# data04 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\KNNtrueNoCV.csv", nrows=300)
# data05 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\SVMtrueNoCV.csv", nrows=300)
# data06 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\GDBTtrueNoCV.csv", nrows=300)
# fig, axs = plt.subplots(2, 3, figsize=(30, 10), dpi=200)
# axs[0, 0].plot(data1, color='red', label="Prediction")
# axs[0, 0].plot(data01, color='blue', label="Label")
# axs[0, 0].set_title('LGBM')
# axs[0, 0].legend(loc=0)
# axs[0, 1].plot(data2, color='red', label="Prediction")
# axs[0, 1].plot(data02, color='blue', label="Label")
# axs[0, 1].set_title('Random Forest')
# # axs[0, 1].legend(loc=0)
# axs[0, 2].plot(data3, color='red', label="Prediction")
# axs[0, 2].plot(data03, color='blue', label="Label")
# axs[0, 2].set_title('DecisionTree')
# # axs[0, 2].legend(loc=0)
# axs[1, 0].plot(data4, color='red', label="Prediction")
# axs[1, 0].plot(data04, color='blue', label="Label")
# axs[1, 0].set_title('KNN')
# # axs[1, 0].legend(loc=0)
# axs[1, 1].plot(data5, color='red', label="Prediction")
# axs[1, 1].plot(data05, color='blue', label="Label")
# axs[1, 1].set_title('SVM')
# # axs[1, 1].legend(loc=0)
# axs[1, 2].plot(data6, color='red', label="Prediction")
# axs[1, 2].plot(data06, color='blue', label="Label")
# axs[1, 2].set_title('GDBT')
# # axs[1, 2].legend(loc=0)
# plt.savefig('E:\paper\\2203\\figures\\REFall.png', bbox_inches='tight', dpi=128)
# plt.savefig('E:\paper\\2203\\figures\\SKBall.png', bbox_inches='tight', dpi=128)

# 单独的图

# data = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\LGBpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\RFpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\DTpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\KNNpredictionNoCV.csv",nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\SVMpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\GDBTpredictionNoCV.csv", nrows=400)
#
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\LGBtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\RFtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\DTtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\KNNtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\SVMtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\GDBTtrueNoCV.csv", nrows=400)
#
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\LGBpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\RFpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\DTpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\KNNpredictionNoCV.csv",nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\SVMpredictionNoCV.csv", nrows=400)
# data = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\GDBTpredictionNoCV.csv", nrows=400)
#
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\reliefF\LGBtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\RFtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\DTtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\KNNtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\SVMtrueNoCV.csv", nrows=400)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\GDBTtrueNoCV.csv", nrows=400)
#
data1 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\LGBpredictionNoCV.csv", nrows=300)
data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\RFpredictionNoCV.csv", nrows=300)
data3 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\DTpredictionNoCV.csv", nrows=300)
data4 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\KNNpredictionNoCV.csv", nrows=300)
data5 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\SVMpredictionNoCV.csv", nrows=300)
data6 = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\GDBTpredictionNoCV.csv", nrows=300)
label_data = pd.read_csv("D:\pythonProject\spark\datas\\result\\reliefF\LGBtrueNoCV.csv", nrows=300)
#
# data1 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\LGBpredictionNoCV.csv", nrows=300)
# data2 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\RFpredictionNoCV.csv", nrows=300)
# data3 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\DTpredictionNoCV.csv", nrows=300)
# data4 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\KNNpredictionNoCV.csv",nrows=300)
# data5 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\SVMpredictionNoCV.csv", nrows=300)
# data6 = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\GDBTpredictionNoCV.csv", nrows=300)
# label_data = pd.read_csv("D:\pythonProject\spark\datas\\result\SKB\LGBtrueNoCV.csv", nrows=300)
x = np.arange(0, 301, step=10)
y = np.arange(0, 6, step=0.5)
plt.figure(figsize=(20, 9), dpi=200)
# plt.plot(data, color='red', label="Prediction")
plt.plot(data1, color='fuchsia', label="lgb")
plt.plot(data2, color='yellow', label="RF")
plt.plot(data3, color='grey', label="DT")
plt.plot(data4, color='m', label="KNN")
plt.plot(data5, color='red', label="SVM")
plt.plot(data6, color='g', label="GDBT")
plt.plot(label_data, color='blue', marker='*', label="Label")
plt.xticks(x)
plt.yticks(y)
plt.legend(loc=0)
# # # plt.xticks(x)
# plt.title("LightGBM")
# # # plt.title("Random Forest")
# # # plt.title("DecisionTree")
# # # plt.title("KNN")
# # # plt.title("SVM")
# # plt.title("GDBT")
plt.ylabel("Status")
# # plt.savefig('E:\paper\\2203\\figures\\LGB.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\RF.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\DT.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\KNN.png', bbox_inches='tight', dpi=128)
# # plt.savefig('E:\paper\\2203\\figures\\SVM.png', bbox_inches='tight', dpi=128)
# plt.savefig('E:\paper\\2203\\figures\\GDBT.png', bbox_inches='tight', dpi=128)
plt.savefig('E:\paper\\2203\\figures\\allREF.png', bbox_inches='tight', dpi=128)
# plt.savefig('E:\paper\\2203\\figures\\allSKB.png', bbox_inches='tight', dpi=128)
plt.show()
